try:
    raise BaseException("This is a test")
except:
    print("caught")
